### PR TITLE
Updates to twilio messaging config

### PR DESCRIPTION
**Pull request by eastandwestwind**
Closes https://github.com/ethyca/fidesdocs/issues/23

### Description of Changes

* [ ] Updates to twilio messaging config copy
* [ ] Added a screenshot of where to obtain secrets from Twilio console

### Pre-Merge Checklist

* [ ] All CI Pipelines Succeeded
* [ ] Issue Requirements are Met
* [ ] Relevant Follow-Up Issues Created

### CODE REVIEW

**Review by sanders41 — APPROVED** [review]
This looks good to me. I do have a question because I noticed this when setting up the test messaging. I thought it was weird we call it Twilio SMS, but to set it up is Twilio messaging. Not a blocker because everything you have here looks correct to me. Just a question if we should make these the same eventually?

**Comment by eastandwestwind** [comment]
Hey @sanders41 what exactly do you mean by `to set it up is Twilio messaging`? 

In my mind, `messaging` across the codebase should refer to the broader Fides capability that include the Twilio sms, Twilio email, and Mailgun services.

**Comment by sanders41** [comment]
Sorry, I didn't mean messaging. To use Twilio SMS you need to add `twilio_text` to the config. Should we be calling it Twilio Text? Or should the config be `twilio_sms`? It was this difference that I found weird.

**Review by NevilleS — APPROVED** [review]

**Review by NevilleS — APPROVED** [review]
Merged in latest main, shipping

**Pull request merged**
