### PR TITLE
Redirect drs support links to under dsr quickstart 

### PR DESCRIPTION
**Pull request by suchiroll**
Closes DOX-245

### Description of Changes

redirects paths under fides/dsr_support/path to fides/dsr_quickstart/dsr_support to workaround an existing bug in search nav 

### Pre-Merge Checklist

* [x ] All CI Pipelines Succeeded
* [ x] Issue Requirements are Met
* [ x] Relevant Follow-Up Issues Created

### CODE REVIEW

**Comment by NevilleS** [comment]
Can you share an example of a dead link on docs.ethyca.com that should be fixed by this redirect? I poked around a bit in the search and didn't find anything to confirm

**Review by NevilleS — APPROVED** [review]
Redirect rule looks good to me - would like to double-check with an existing dead link but couldn't find any!

**Comment by suchiroll** [comment]
@NevilleS 
a bit annoying to recreate but if you if you search 'graphs'  in the nav, it'll attempt to link you to 
https://fidesdocs-git-search-bug-ethyca.vercel.app/fides/dsr_support/query_execution#graphs-and-traversals 

which would normally turn up a 404, but with the redirect in place it routes them to the right page. 

I believe flex search has been turned off on prod right now, so you can't verify the dead link 

you can verify it was broken here:
https://fidesdocs-dz7uyl1qh-ethyca.vercel.app/fides/overview

**Comment by NevilleS** [comment]
Perfect, thanks! Tested on those two deploy branches...
* Search "graphs" on https://fidesdocs-dz7uyl1qh-ethyca.vercel.app
* Get dead link: https://fidesdocs-dz7uyl1qh-ethyca.vercel.app/fides/dsr_support/query_execution#graphs-and-traversals
* Transpose that to your new branch: https://fidesdocs-git-search-bug-ethyca.vercel.app/fides/dsr_support/query_execution#graphs-and-traversals

Redirect works as advertised, ship it

**Pull request merged**
