### PR TITLE
Adding Statsig Enterprise Documentation

### PR DESCRIPTION
**Pull request by MarcGEthyca**
Closes n/a

### Description of Changes

* [x] _Adding Statsig Enterprise documentation using the new layout_

### Pre-Merge Checklist

* [X] All CI Pipelines Succeeded
* [X] Issue Requirements are Met
* [X] Relevant Follow-Up Issues Created

### CODE REVIEW

**Comment by Kelsey-Ethyca** [comment]
Should `Statsig user ID field` be included in the docs? 

Screenshot 2024-01-10 at 10 01 28 AM

**Comment by Kelsey-Ethyca** [comment]
When does the customer need `Statsig Enterprise Console API Key`?
Screenshot 2024-01-10 at 10 02 23 AM

**Comment by MarcGEthyca** [comment]
> When does the customer need `Statsig Enterprise Console API Key`? Screenshot 2024-01-10 at 10 02 23 AM

Nope, the console API key is no longer needed! Good spot!

**Comment by MarcGEthyca** [comment]
> Should `Statsig user ID field` be included in the docs?
> 
> Screenshot 2024-01-10 at 10 01 28 AM

Yes I think so, though I'm thinking we may want to change the wording around it? In Statsig's case, we don't have an email address! So we created an external reference that can be filled in by customers to basically ask them to point us to where the Statsig user id can be translated back into an email address.

**Review by Kelsey-Ethyca — APPROVED** [review]
🦖

**Pull request merged**
